//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoutine
    {
        public int RoutineID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string DayNam { get; set; }
        public Nullable<System.DateTime> StartingTime { get; set; }
        public Nullable<System.DateTime> EndingTiem { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual SubjectInfo SubjectInfo { get; set; }
    }
}
