//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.MARKS = new HashSet<MARK>();
        }
    
        public int ExamID { get; set; }
        public string ExamName { get; set; }
        public string ExamType { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual ICollection<MARK> MARKS { get; set; }
    }
}
