//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARK
    {
        public int MarkID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual tblClass tblClass { get; set; }
        public virtual Student Student { get; set; }
        public virtual SubjectInfo SubjectInfo { get; set; }
    }
}
