//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int ParentID { get; set; }
        public string ParentName { get; set; }
        public string ParentAddress { get; set; }
        public string ParentMobile { get; set; }
        public string ParentLandPhone { get; set; }
        public string ParentEmail { get; set; }
        public string ParentPassword { get; set; }
        public string ParentWork { get; set; }
        public string ParentPhoto { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
