//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolManagementDBEntities : DbContext
    {
        public SchoolManagementDBEntities()
            : base("name=SchoolManagementDBEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassRoutine> ClassRoutines { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<SECTION> SECTIONs { get; set; }
        public virtual DbSet<SubjectInfo> SubjectInfoes { get; set; }
        public virtual DbSet<tblClass> tblClasses { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Attendence> Attendences { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<MARK> MARKS { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentInformation> StudentInformations { get; set; }
        public virtual DbSet<TeacherInformationview> TeacherInformationviews { get; set; }
    }
}
