//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTION
    {
        public SECTION()
        {
            this.ClassRoutines = new HashSet<ClassRoutine>();
            this.tblClasses = new HashSet<tblClass>();
            this.Students = new HashSet<Student>();
        }
    
        public int SectionID { get; set; }
        public string SectionName { get; set; }
    
        public virtual ICollection<ClassRoutine> ClassRoutines { get; set; }
        public virtual ICollection<tblClass> tblClasses { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
