//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Attendences = new HashSet<Attendence>();
            this.MARKS = new HashSet<MARK>();
        }
    
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> StudentRoll { get; set; }
        public Nullable<System.DateTime> StudentBirthday { get; set; }
        public string StudentAddress { get; set; }
        public string StudentPhone { get; set; }
        public string StudentEmail { get; set; }
        public string StudentPassword { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string StudentImage { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> AttID { get; set; }
    
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual Attendence Attendence { get; set; }
        public virtual ICollection<MARK> MARKS { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual tblClass tblClass { get; set; }
    }
}
