//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
        public string ClassName { get; set; }
        public string SectionName { get; set; }
        public Nullable<System.DateTime> DateOfAdmission { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentMiddleName { get; set; }
        public string StudentLastName { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public System.DateTime DOB { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string RelationWithGardians { get; set; }
    }
}
