//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectInfo
    {
        public SubjectInfo()
        {
            this.ClassRoutines = new HashSet<ClassRoutine>();
            this.MARKS = new HashSet<MARK>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public string AuthorName { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual ICollection<ClassRoutine> ClassRoutines { get; set; }
        public virtual tblClass tblClass { get; set; }
        public virtual ICollection<MARK> MARKS { get; set; }
    }
}
