//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClass
    {
        public tblClass()
        {
            this.ClassRoutines = new HashSet<ClassRoutine>();
            this.SubjectInfoes = new HashSet<SubjectInfo>();
            this.Attendences = new HashSet<Attendence>();
            this.Exams = new HashSet<Exam>();
            this.MARKS = new HashSet<MARK>();
            this.Students = new HashSet<Student>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> TeacharID { get; set; }
    
        public virtual ICollection<ClassRoutine> ClassRoutines { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual ICollection<SubjectInfo> SubjectInfoes { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<MARK> MARKS { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
