//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAPIMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.tblClasses = new HashSet<tblClass>();
        }
    
        public int TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string TeacherAddress { get; set; }
        public string TeacherPhone { get; set; }
        public string TeacherEmail { get; set; }
        public string TeacherPhoto { get; set; }
        public string TeacherDesignation { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<tblClass> tblClasses { get; set; }
    }
}
